params:
  test: testKeyword
  epochs: 30
  no_classes: 10
  input_shape: [28,28]
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000

artifacts:
  artifacts_dir: atrifacts
  model_dir: model
  plots_dir: plots
  checkpoints_dir: checkpoints

logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorflow_logs: tensorflow_logs
